from flask import Flask, jsonify
from flask_cors import CORS

import json
from dotenv import load_dotenv
import os

from functools import lru_cache
import datetime
import trade_engine
import backend_auth
from flask import request

load_dotenv()

app = Flask(__name__)
# Enable CORS for all routes (since frontend is file-based or separate)
CORS(app)

@app.route('/api/history/<ticker>')
def get_history(ticker):
    try:
        import os
        import json
        import sqlite3
        
        ticker = ticker.upper()
        print(f"Fetching history for {ticker} from local stock_vault.db...")
        
        # 1. Fetch Company Meta Data (from local JSON)
        company_name = ticker
        try:
            with open('sp500.json', 'r') as f:
                sp500 = json.load(f)
                for item in sp500:
                    if item.get('ticker') == ticker:
                        company_name = item.get('company', ticker)
                        break
        except Exception as e:
            print(f"Could not load sp500.json for company name: {e}")

        # 2. Fetch Price History from stock_vault.db
        db_path = os.path.join("data", "stock_vault.db")
        if not os.path.exists(db_path):
             return jsonify({"error": "Local Database not found"}), 500
             
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Order by date ASC to match chronological expectation of charts
        cursor.execute("SELECT date, close, adjClose, volume FROM prices WHERE ticker = ? ORDER BY date ASC", (ticker,))
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            print(f"No history found in database for {ticker}")
            return jsonify({"symbol": ticker, "companyName": company_name, "history": []}), 200
            
        print(f"Retrieved {len(rows)} data points from vault for {ticker}")
        
        # Format: [{"date": "YYYY-MM-DD", "price": 123.45, "volume": 12345}, ...]
        formatted_history = []
        for row in rows:
            date_str, close_price, adj_close, vol = row
            # Prefer adjusted close if available
            price = adj_close if adj_close is not None else close_price
            
            if date_str and price is not None:
                # Tiingo dates often map cleanly; ensure no timestamps interfere
                d_str = date_str.split('T')[0] if 'T' in date_str else date_str.split(' ')[0]
                formatted_history.append({
                    "date": d_str,
                    "price": round(float(price), 2),
                    "volume": float(vol) if vol is not None else 0
                })
            
        return jsonify({
            "symbol": ticker,
            "companyName": company_name,
            "history": formatted_history
        })
        
    except Exception as e:
        print(f"Error fetching {ticker}: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/dashboard')
def get_dashboard():
    try:
        # Serve the JSON file generated by api_dashboard.py
        import json
        with open('dashboard_final.json', 'r') as f:
            data = json.load(f)
            
        # Hardcoded Sector Map for Heatmap
        sector_map = {
            'AAPL': 'Technology', 'MSFT': 'Technology', 'NVDA': 'Technology', 'GOOGL': 'Technology',
            'AMZN': 'Consumer Cyclical', 'TSLA': 'Consumer Cyclical', 'META': 'Technology',
            'JPM': 'Financials', 'BAC': 'Financials', 'WFC': 'Financials', 'C': 'Financials',
            'XOM': 'Energy', 'CVX': 'Energy', 'COP': 'Energy',
            'JNJ': 'Healthcare', 'PFE': 'Healthcare', 'UNH': 'Healthcare', 'LLY': 'Healthcare',
            'PG': 'Consumer Defensive', 'KO': 'Consumer Defensive', 'PEP': 'Consumer Defensive',
            'COST': 'Consumer Defensive', 'WMT': 'Consumer Defensive',
            'BA': 'Industrials', 'CAT': 'Industrials', 'GE': 'Industrials',
            'DIS': 'Communication Services', 'NFLX': 'Communication Services',
            'AMD': 'Technology', 'INTC': 'Technology', 'QCOM': 'Technology',
            'GS': 'Financials', 'MS': 'Financials'
        }
        
        # Inject Sector
        if 'signals' in data:
            for signal in data['signals']:
                ticker = signal.get('Ticker')
                signal['Sector'] = sector_map.get(ticker, 'Unclassified')
                
        return jsonify(data)
    except Exception as e:
         return jsonify({"error": "Dashboard data not ready", "details": str(e)}), 500

def get_live_price(ticker):
    """
    Price fetcher:
    1. Only uses cached dashboard_final.json (Tiingo data) for consistency and to save API calls.
    """
    
    try:
        # Method 1: Check existing dashboard cache
        with open('dashboard_final.json', 'r') as f:
            data = json.load(f)
            for signal in data.get('signals', []):
                if signal.get('Ticker') == ticker:
                    if 'Price' in signal:
                         # Handle 0.0 or None prices
                         p = float(signal['Price'])
                         if p > 0:
                             return p
    except Exception as e:
        print(f"Cache miss or error for {ticker}: {e}")

    return None

@app.route('/api/portfolio', methods=['GET'])
def get_portfolio_route():
    # 1. Auth
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Missing or invalid token"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    
    if not uid:
        return jsonify({"error": "Invalid token"}), 401
        
    try:
        # 2. Get Data
        pf_data = trade_engine.get_portfolio(uid)
        
        # 3. Enrich with Live Prices (Unrealized P&L)
        holdings = pf_data.get('holdings', [])
        
        if holdings:
            total_value = 0.0
            
            for h in holdings:
                t = h['ticker']
                # Use robust fetcher
                current_price = get_live_price(t)
                
                if current_price is None:
                    current_price = h['avg_price'] # Fallback to cost basis
                
                h['current_price'] = round(current_price, 2)
                h['market_value'] = round(current_price * h['quantity'], 2)
                h['return_pct'] = round(((current_price - h['avg_price']) / h['avg_price']) * 100, 2)
                h['unrealized_pl'] = round((current_price - h['avg_price']) * h['quantity'], 2)
                
                total_value += h['market_value']
                
            pf_data['holdings'] = holdings
            pf_data['total_portfolio_value'] = round(total_value + pf_data['cash'], 2)
            pf_data['total_investment'] = round(sum(h['avg_price'] * h['quantity'] for h in holdings), 2)
            pf_data['total_unrealized_pl'] = round(sum(h['unrealized_pl'] for h in holdings), 2)
            
        else:
             pf_data['total_portfolio_value'] = pf_data['cash']
             pf_data['total_investment'] = 0.0
             pf_data['total_unrealized_pl'] = 0.0
             
        return jsonify(pf_data)
        
    except Exception as e:
        print(f"Portfolio Error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/api/trade', methods=['POST'])
def trade_route():
    try:
        # 1. Auth
        auth_header = request.headers.get('Authorization')
        if not auth_header or not auth_header.startswith("Bearer "):
             return jsonify({"error": "Unauthorized"}), 401
        
        token = auth_header.split(" ")[1]
        uid = backend_auth.verify_token(token)
        if not uid: return jsonify({"error": "Invalid User"}), 401
        
        # 2. Input
        data = request.json
        ticker = data.get('ticker')
        action = data.get('action') # BUY / SELL
        quantity = data.get('quantity')
        
        if not all([ticker, action, quantity]):
            return jsonify({"error": "Missing fields"}), 400
            
        try:
            quantity = int(quantity)
            if quantity <= 0: raise ValueError
        except:
            return jsonify({"error": "Invalid quantity"}), 400
            
        # 3. Fetch Live Price (Authoritative)
        live_price = get_live_price(ticker)
        
        if not live_price:
             return jsonify({"error": "Could not fetch live price. Market data unavailable."}), 500
             
        # 4. Execute
        result = trade_engine.execute_trade(uid, ticker, action, quantity, live_price)
        
        if result['status'] == 'success':
            return jsonify({
                "message": f"Successfully {action} {quantity} {ticker} @ ${live_price:.2f}",
                "new_balance": result['new_balance']
            })
        else:
            return jsonify({"error": result['message']}), 400
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({"error": f"Internal Server Error: {str(e)}"}), 500

@app.route('/api/portfolio/<ticker>', methods=['DELETE'])
def delete_position_route(ticker):
    # 1. Auth
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    if not ticker:
         return jsonify({"error": "Missing ticker"}), 400
         
    try:
        trade_engine.delete_position(uid, ticker)
        return jsonify({"message": f"Deleted position {ticker}"})
    except Exception as e:
         return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    # Run on port 5001 to avoid conflicts with common 5000
    print("🚀 History API running on http://localhost:5001")
    app.run(port=5001, debug=True)
