from flask import Flask, jsonify
from flask_cors import CORS

import json
from dotenv import load_dotenv
import os
import threading
import time
from functools import lru_cache
import datetime
import trade_engine
import backend_auth
from flask import request
import database

load_dotenv()

app = Flask(__name__)
CORS(app)

import traceback

# Firebase Project Verification
try:
    from firebase_admin import firestore
    db = firestore.client()
    # Handle different library versions for project_id
    project_id = getattr(db, 'project', None) or getattr(db, 'project_id', 'Unknown')
    print(f"🔥 [Firebase] Connected to Project: {project_id}")
except Exception as e:
    print(f"❌ [Firebase] Initialization failed: {e}")

@app.route('/api/history/<ticker>')
def get_history(ticker):
    try:
        import os
        import json
        import sqlite3
        
        ticker = ticker.upper()
        print(f"Fetching history for {ticker} from local stock_vault.db...")
        
        # 1. Fetch Company Meta Data (from local JSON)
        company_name = ticker
        try:
            with open('sp500.json', 'r') as f:
                sp500 = json.load(f)
                for item in sp500:
                    if item.get('ticker') == ticker:
                        company_name = item.get('company', ticker)
                        break
        except Exception as e:
            print(f"Could not load sp500.json for company name: {e}")

        # 2. Fetch Price History from stock_vault.db
        db_path = os.path.join("data", "stock_vault.db")
        if not os.path.exists(db_path):
             return jsonify({"error": "Local Database not found"}), 500
             
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Order by date ASC to match chronological expectation of charts
        cursor.execute("SELECT date, close, adjClose, volume FROM prices WHERE ticker = ? ORDER BY date ASC", (ticker,))
        rows = cursor.fetchall()
        conn.close()
        
        if not rows:
            print(f"No history found in database for {ticker}")
            return jsonify({"symbol": ticker, "companyName": company_name, "history": []}), 200
            
        print(f"Retrieved {len(rows)} data points from vault for {ticker}")
        
        # Format: [{"date": "YYYY-MM-DD", "price": 123.45, "volume": 12345}, ...]
        formatted_history = []
        for row in rows:
            date_str, close_price, adj_close, vol = row
            # Prefer adjusted close if available
            price = adj_close if adj_close is not None else close_price
            
            if date_str and price is not None:
                # Tiingo dates often map cleanly; ensure no timestamps interfere
                d_str = date_str.split('T')[0] if 'T' in date_str else date_str.split(' ')[0]
                formatted_history.append({
                    "date": d_str,
                    "price": round(float(price), 2),
                    "volume": float(vol) if vol is not None else 0
                })
            
        return jsonify({
            "symbol": ticker,
            "companyName": company_name,
            "history": formatted_history
        })
        
    except Exception as e:
        print(f"Error fetching {ticker}: {e}")
        # Return 200 with error info to prevent frontend crashes
        return jsonify({"symbol": ticker, "companyName": ticker, "history": [], "error": str(e)}), 200

@app.route('/api/dashboard')
def get_dashboard():
    try:
        # Serve the JSON file generated by api_dashboard.py
        import json
        with open('dashboard_final.json', 'r') as f:
            data = json.load(f)
            
        # Hardcoded Sector Map for Heatmap
        sector_map = {
            'AAPL': 'Technology', 'MSFT': 'Technology', 'NVDA': 'Technology', 'GOOGL': 'Technology',
            'AMZN': 'Consumer Cyclical', 'TSLA': 'Consumer Cyclical', 'META': 'Technology',
            'JPM': 'Financials', 'BAC': 'Financials', 'WFC': 'Financials', 'C': 'Financials',
            'XOM': 'Energy', 'CVX': 'Energy', 'COP': 'Energy',
            'JNJ': 'Healthcare', 'PFE': 'Healthcare', 'UNH': 'Healthcare', 'LLY': 'Healthcare',
            'PG': 'Consumer Defensive', 'KO': 'Consumer Defensive', 'PEP': 'Consumer Defensive',
            'COST': 'Consumer Defensive', 'WMT': 'Consumer Defensive',
            'BA': 'Industrials', 'CAT': 'Industrials', 'GE': 'Industrials',
            'DIS': 'Communication Services', 'NFLX': 'Communication Services',
            'AMD': 'Technology', 'INTC': 'Technology', 'QCOM': 'Technology',
            'GS': 'Financials', 'MS': 'Financials'
        }
        
        # Inject Sector
        if 'signals' in data:
            for signal in data['signals']:
                ticker = signal.get('Ticker')
                signal['Sector'] = sector_map.get(ticker, 'Unclassified')
                
        return jsonify(data)
    except Exception as e:
         return jsonify({"error": "Dashboard data not ready", "details": str(e)}), 500

def get_live_price(ticker):
    """
    Price fetcher:
    1. Only uses cached dashboard_final.json (Tiingo data) for consistency and to save API calls.
    """
    
    try:
        # Method 1: Check existing dashboard cache
        with open('dashboard_final.json', 'r') as f:
            data = json.load(f)
            for signal in data.get('signals', []):
                if signal.get('Ticker') == ticker:
                    if 'Price' in signal:
                         # Handle 0.0 or None prices
                         p = float(signal['Price'])
                         if p > 0:
                             return p
    except Exception as e:
        print(f"Cache miss or error for {ticker}: {e}")

    return None

@app.route('/api/portfolio', methods=['GET'])
def get_portfolio_route():
    # 1. Auth
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Missing or invalid token"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    
    if not uid:
        return jsonify({"error": "Invalid token"}), 401
        
    try:
        # 2. Get Data
        sim_id = request.args.get('simulationId')
        print(f"📊 [API] Fetching portfolio for UID: {uid}, Simulation ID: {sim_id or 'DEFAULT'}")
        
        pf_data = trade_engine.get_portfolio(uid, simulation_id=sim_id)
        
        if 'error' in pf_data:
             return jsonify(pf_data), 404
        
        # 3. Enrich with Live Prices (Unrealized P&L)
        holdings = pf_data.get('holdings', [])
        
        if holdings:
            total_value = 0.0
            
            for h in holdings:
                t = h['ticker']
                # Use robust fetcher
                current_price = get_live_price(t)
                
                if current_price is None:
                    current_price = h['avg_price'] # Fallback to cost basis
                
                h['current_price'] = round(current_price, 2)
                h['market_value'] = round(current_price * h['quantity'], 2)
                h['return_pct'] = round(((current_price - h['avg_price']) / h['avg_price']) * 100, 2)
                h['unrealized_pl'] = round((current_price - h['avg_price']) * h['quantity'], 2)
                
                total_value += h['market_value']
                
            pf_data['holdings'] = holdings
            pf_data['total_portfolio_value'] = round(total_value + pf_data['cash'], 2)
            pf_data['total_investment'] = round(sum(h['avg_price'] * h['quantity'] for h in holdings), 2)
            pf_data['total_unrealized_pl'] = round(sum(h['unrealized_pl'] for h in holdings), 2)
            
        else:
             pf_data['total_portfolio_value'] = pf_data['cash']
             pf_data['total_investment'] = 0.0
             pf_data['total_unrealized_pl'] = 0.0
             
        return jsonify(pf_data)
        
    except Exception as e:
        print(f"Portfolio Error: {e}")
        # Return 200 with error to prevent loud frontend crashes
        return jsonify({"error": str(e), "holdings": [], "cash": 0}), 200

@app.route('/api/trade', methods=['POST'])
def trade_route():
    try:
        # 1. Auth
        auth_header = request.headers.get('Authorization')
        if not auth_header or not auth_header.startswith("Bearer "):
             return jsonify({"error": "Unauthorized"}), 401
        
        token = auth_header.split(" ")[1]
        uid = backend_auth.verify_token(token)
        if not uid: return jsonify({"error": "Invalid User"}), 401
        
        # 2. Input
        data = request.json
        ticker = data.get('ticker')
        action = data.get('action') # BUY / SELL
        quantity = data.get('quantity')
        sim_id = data.get('simulationId')
        
        if not all([ticker, action, quantity, sim_id]):
            return jsonify({"error": "Missing fields (ticker, action, quantity, simulationId)"}), 400
            
        try:
            quantity = int(quantity)
            if quantity <= 0: raise ValueError
        except:
            return jsonify({"error": "Invalid quantity"}), 400
            
        # 3. Fetch Live Price (Authoritative)
        live_price = get_live_price(ticker)
        
        if not live_price:
             # Using 400 instead of 500 for unavailable prices
             return jsonify({"error": "Could not fetch live price. Market data unavailable for this ticker."}), 400
             
        # 4. Execute
        print(f"💸 [API] Executing {action} for {quantity} {ticker} in Simulation: {sim_id}")
        result = trade_engine.execute_trade(uid, sim_id, ticker, action, quantity, live_price)
        
        if result['status'] == 'success':
            return jsonify({
                "message": f"Successfully {action} {quantity} {ticker} @ ${live_price:.2f}",
                "new_balance": result['new_balance']
            })
        else:
            return jsonify({"error": result['message']}), 400
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({"error": f"Internal Server Error: {str(e)}"}), 500

@app.route('/api/portfolio/<ticker>', methods=['DELETE'])
def delete_position_route(ticker):
    # 1. Auth
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    if not ticker:
         return jsonify({"error": "Missing ticker"}), 400
         
    try:
        sim_id = request.args.get('simulationId')
        if not sim_id:
             return jsonify({"error": "Missing simulationId"}), 400
             
        trade_engine.delete_position(uid, sim_id, ticker)
        return jsonify({"message": f"Deleted position {ticker}"})
    except Exception as e:
         return jsonify({"error": str(e)}), 500

# --- Simulation Management Routes ---

@app.route('/api/simulations', methods=['GET'])
def list_simulations_route():
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    try:
        sims = trade_engine.list_simulations(uid)
        return jsonify({"simulations": sims})
    except Exception as e:
        print(f"❌ [API Error] simulations list hit a crash:")
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

@app.route('/api/simulations', methods=['POST'])
def create_simulation_route():
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    data = request.json or {}
    name = data.get('name')
    initial_cash = data.get('initial_cash', 0.0)
    
    if not name:
        return jsonify({"error": "Name is required"}), 400
        
    try:
        sim_id = trade_engine.create_simulation(uid, name, initial_cash)
        return jsonify({"id": sim_id, "name": name, "cash": initial_cash}), 201
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/simulations/<sim_id>', methods=['PATCH'])
def rename_simulation_route(sim_id):
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    data = request.json or {}
    name = data.get('name')
    if not name:
        return jsonify({"error": "Name is required"}), 400
        
    try:
        trade_engine.rename_simulation(uid, sim_id, name)
        return jsonify({"message": "Successfully renamed", "id": sim_id, "name": name})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/simulations/<sim_id>', methods=['DELETE'])
def delete_simulation_route(sim_id):
    auth_header = request.headers.get('Authorization')
    if not auth_header or not auth_header.startswith("Bearer "):
         return jsonify({"error": "Unauthorized"}), 401
    
    token = auth_header.split(" ")[1]
    uid = backend_auth.verify_token(token)
    if not uid: return jsonify({"error": "Invalid User"}), 401
    
    try:
        trade_engine.delete_simulation(uid, sim_id)
        return jsonify({"message": "Successfully deleted", "id": sim_id})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/stocks/all', methods=['GET'])
def get_all_stocks_route():
    try:
        conn = database.get_connection()
        cursor = conn.cursor()
        cursor.execute("SELECT ticker, company_name FROM company_meta ORDER BY ticker")
        results = [{"ticker": row[0], "name": row[1]} for row in cursor.fetchall()]
        conn.close()
        return jsonify(results)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/search', methods=['GET'])
def search_stocks():
    query = request.args.get('q', '').upper().strip()
    if not query:
        return jsonify([])
        
    try:
        with open('sp500.json', 'r') as f:
            sp500 = json.load(f)
            
        matches = []
        for item in sp500:
            ticker = item.get('ticker', '').upper()
            name = item.get('name', '').upper()
            
            if query in ticker or query in name:
                # Add price info from cache
                price = get_live_price(ticker)
                matches.append({
                    "Ticker": ticker,
                    "Name": item.get('name'),
                    "Price": price or 0.0,
                    # Provide minimal fields needed by StockCard/Modal
                    "Signal": "Watchlist Candidate",
                    "Headline": f"Analyzing {ticker} for potential strategy entry."
                })
                if len(matches) >= 10: break # Peak efficiency
                
        return jsonify(matches)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

import pandas as pd
import requests
from io import StringIO

def fetch_recent_data(ticker, start_date_str, conn):
    """
    Fetch recent data for a ticker from Tiingo (with robust handling and 60 req/hr limit in mind).
    """
    api_key = os.environ.get('TIINGO_API_KEY')
    if not api_key: return 0
    
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {api_key}'
    }
    fetch_ticker = ticker.replace('.', '-')
    
    try:
        start_date = datetime.datetime.strptime(start_date_str, "%Y-%m-%d")
    except ValueError:
        start_date = datetime.datetime.strptime(start_date_str[:10], "%Y-%m-%d")
        
    next_day = start_date + datetime.timedelta(days=1)
    next_day_str = next_day.strftime("%Y-%m-%d")
    today_str = datetime.datetime.now().strftime("%Y-%m-%d")
    
    if next_day_str >= today_str:
        return 0 
        
    url = f"https://api.tiingo.com/tiingo/daily/{fetch_ticker}/prices?startDate={next_day_str}&format=csv"
    
    max_retries = 3
    for attempt in range(max_retries):
        try:
            # Added 15s timeout
            response = requests.get(url, headers=headers, timeout=15)
            
            if response.status_code == 429:
                wait_time = (attempt + 1) * 120 # Wait longer on 429
                print(f"⚠️ Rate limited (429) for {ticker}. Retrying in {wait_time}s...")
                time.sleep(wait_time)
                continue
                
            if response.status_code == 404: 
                return 0
                
            response.raise_for_status()
            
            csv_data = StringIO(response.text)
            df = pd.read_csv(csv_data)
            
            if df.empty: return 0
            
            df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
            df['ticker'] = ticker
            
            # Explicit lock not strictly needed for separate thread unless multiple updaters,
            # but pandas to_sql is generally safe here.
            df.to_sql("prices", conn, if_exists="append", index=False)
            return len(df)
            
        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as te:
            print(f"⚠️ Connection issue for {ticker} (Attempt {attempt+1}/{max_retries}): {te}")
            if attempt < max_retries - 1: time.sleep(10 * (attempt + 1))
            else: break
        except Exception as e:
            print(f"❌ Critical error updating {ticker}: {e}")
            break
            
    return 0

def auto_update_vault():
    print("\n🔄 [Background] Checking stock_vault.db for missing daily closes...")
    db_path = os.path.join("data", "stock_vault.db")
    if not os.path.exists(db_path):
        print("   Database not found, skipping auto-update.")
        return
        
    import sqlite3
    import pandas as pd
    
    conn = sqlite3.connect(db_path, check_same_thread=False)
    query = "SELECT ticker, MAX(date) as max_date FROM prices GROUP BY ticker"
    try:
        df_max = pd.read_sql_query(query, conn)
    except Exception as e:
        print(f"   Error reading DB: {e}")
        conn.close()
        return
        
    updated_tickers = 0
    total_new_rows = 0
    
    for _, row in df_max.iterrows():
        ticker = row['ticker']
        max_date_str = str(row['max_date'])[:10]
        
        new_rows = fetch_recent_data(ticker, max_date_str, conn)
        if new_rows > 0:
            updated_tickers += 1
            total_new_rows += new_rows
            # STRICT RATE LIMITING: 61s delay between SUCCESSFUL requests to respect 60 req/hr
            print(f"   Fetched {new_rows} rows for {ticker}. Waiting 61s for Tiingo limit...")
            time.sleep(61)
        else:
            # Small politeness delay regardless
            time.sleep(1)
            
    conn.close()
    
    if updated_tickers > 0:
        print(f"✅ Background Auto-Update complete: Added {total_new_rows} new daily closes across {updated_tickers} tickers.")
    else:
        print("✅ Vault is fully up to date! No new closes to fetch.")


if __name__ == '__main__':
    # Run on port 5001 to avoid conflicts with common 5000
    print("🚀 History API running on http://localhost:5001")
    
    # Werkzeug runs the script twice in debug mode. This lock ensures the background thread only fires once.
    if os.environ.get('WERKZEUG_RUN_MAIN') != 'true':
        update_thread = threading.Thread(target=auto_update_vault, daemon=True)
        update_thread.start()
        print("⚙️  Background update thread started.")
        
    app.run(host='0.0.0.0', port=5001, debug=True)
